version: "3.9"
services:
  backend:
    build:
      context: .
    image: blog-backend:latest
    container_name: blog-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - PORT=8000
      - FLASK_RUN_HOST=0.0.0.0
      - FLASK_RUN_PORT=8000
      - PYTHONUNBUFFERED=1
    volumes:
      - ./uploads:/app/uploads
      - ./articles.json:/app/articles.json
    restart: unless-stopped
